# PyQt/PySide ImportError: DLL load failed while importing Shiboken



[https://blog.csdn.net/John_Lenon/article/details/133434144](https://blog.csdn.net/John_Lenon/article/details/133434144)

原因:PySide2在python 3.8.0中无法正常工作，提高python版本即可。

3.8.1即可。